name: Keep API Alive
on:
  schedule:
    - cron: '* * * * *' # Runs every minute
  workflow_dispatch: # Adds manual trigger button in GitHub UI
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: |
          curl -s https://resume-pdf-endpoint.onrender.com/
